import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BlogsProvider } from "@/Context/blogcontext"
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Analytics } from "@vercel/analytics/next"
import Script from "next/script";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-B91X37J8R8"
        />
        <Script id="gtag-init" strategy="afterInteractive">
          {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-B91X37J8R8');
  `}
        </Script>

      </head>


      <body
        className=' bg-whiteoff  !overflow-x-hidden'
      >
        <Analytics />
        <Navbar />
        <BlogsProvider>

          {children}
        </BlogsProvider>
        <Footer />

      </body>
    </html>
  );
}
